"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const http=require("node:http");
const {discoverApiProject,contractFromDiscovery,contractFromPlan,createHttpDriver,captureApi}=require("../src/adapters/api");

test("API discovery parses local OpenAPI JSON without calling endpoints",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-api-"));fs.writeFileSync(path.join(dir,"openapi.json"),JSON.stringify({openapi:"3.1.0",info:{title:"Fixture API",version:"1"},servers:[{url:"https://user:secret@example.test/api?token=abc"}],components:{securitySchemes:{bearerAuth:{type:"http",scheme:"bearer"}}},paths:{"/health":{get:{operationId:"health",responses:{"200":{description:"ok"}}}}}}));const discovery=discoverApiProject(dir);assert.equal(discovery.signals.json_specification_loaded,true);assert.equal(discovery.signals.operation_count,1);assert.deepEqual(discovery.signals.security_schemes,["bearerAuth"]);assert.ok(!discovery.api.servers[0].includes("secret"));const contract=contractFromDiscovery(discovery,{product:"Fixture"});assert.equal(contract.review_required,true);assert.ok(contract.checks.every((check)=>check.provenance.reviewed===false));});

test("API discovery parses OpenAPI YAML directly",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-api-yaml-"));fs.writeFileSync(path.join(dir,"openapi.yaml"),`openapi: 3.1.0\ninfo:\n  title: YAML Fixture\n  version: '1'\npaths:\n  /health:\n    get:\n      operationId: health\n      responses:\n        '200':\n          description: ok\n`);const discovery=discoverApiProject(dir);assert.equal(discovery.signals.yaml_specification_loaded,true);assert.equal(discovery.signals.yaml_requires_conversion,false);assert.equal(discovery.signals.specification_format,"yaml");assert.equal(discovery.signals.operation_count,1);assert.equal(discovery.api.title,"YAML Fixture");});

test("API capture exports shape instead of body and can verify downstream state without exporting it",async()=>{let applied=false;const server=http.createServer((req,res)=>{res.setHeader("content-type","application/json");if(req.method==="POST"&&req.url.startsWith("/apply")){applied=true;res.end(JSON.stringify({accepted:true,secret:"write-secret"}));return;}if(req.method==="GET"&&req.url.startsWith("/state")){res.end(JSON.stringify({applied,secret:"downstream-secret",items:[1,2]}));return;}res.statusCode=404;res.end(JSON.stringify({error:"not-found"}));});await new Promise((resolve)=>server.listen(0,"127.0.0.1",resolve));const {port}=server.address();try{const plan={protocol:"calibration-api-plan/0.5",requests:[{id:"apply",method:"POST",url:`http://127.0.0.1:${port}/apply?token=hidden`,headers:{authorization:"Bearer super-secret"},body:{secret:"request-secret"},allow_effectful:true,expected_status:[200],verify:[{id:"state",method:"GET",url:`http://127.0.0.1:${port}/state`,expected_status:[200],expected_content_type:"application/json",assertions:[{pointer:"/applied",operator:"equals",expected:true},{pointer:"/items",operator:"length",expected:2},{pointer:"/secret",operator:"exists"}]}]}]};const contract=contractFromPlan(plan,{product:"Fixture API"});assert.ok(contract.checks.some((check)=>check.id==="api.apply.verify.state.assert.1"));const result=await captureApi({plan,driver:createHttpDriver(),options:{allowEffectful:true}});assert.equal(result.observations.find((item)=>item.id==="api.apply.verify.state.assert.1").value,true);assert.equal(result.observations.find((item)=>item.id==="api.apply.verify.state.assert.2").value,true);const serialized=JSON.stringify(result);for(const secret of ["super-secret","request-secret","write-secret","downstream-secret","hidden"])assert.ok(!serialized.includes(secret),`leaked ${secret}`);assert.ok(serialized.includes("expected_sha256"));}finally{await new Promise((resolve)=>server.close(resolve));}});

test("API effectful methods require plan and command consent",async()=>{const plan={protocol:"calibration-api-plan/0.5",requests:[{id:"write",method:"POST",url:"https://example.invalid",allow_effectful:true}]};await assert.rejects(()=>captureApi({plan,driver:{request:async()=>({completed:true})},options:{allowEffectful:false}}),/blocked/);});

test("API verifiers are always read-only",()=>{assert.throws(()=>contractFromPlan({protocol:"calibration-api-plan/0.5",requests:[{id:"write",method:"POST",url:"https://example.test",allow_effectful:true,verify:[{id:"bad",method:"POST",url:"https://example.test/verify"}]}]}),/verification.*safe/i);});
