"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {discoverBrowserExtensionProject,scanSources}=require("../src/adapters/browser-extension/discover");
const {contractFromDiscovery}=require("../src/adapters/browser-extension/contract");
const {captureBrowserExtension}=require("../src/adapters/browser-extension/capture");
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-ext-"));fs.writeFileSync(path.join(dir,"manifest.json"),JSON.stringify({manifest_version:3,name:"Fixture",version:"1.0.0",permissions:["storage","scripting","activeTab"],optional_permissions:["downloads"],host_permissions:["https://example.test/*"],background:{service_worker:"service-worker.js"},action:{default_popup:"popup.html"},options_page:"options.html",content_scripts:[{matches:["https://example.test/*"],js:["content.js"],world:"ISOLATED"}]}));fs.writeFileSync(path.join(dir,"service-worker.js"),"chrome.runtime.onInstalled.addListener(()=>chrome.storage.local.set({ready:true})); chrome.tabs.query({active:true}); chrome.scripting.getRegisteredContentScripts();");fs.writeFileSync(path.join(dir,"content.js"),"document.documentElement.dataset.fixture='1';");fs.writeFileSync(path.join(dir,"popup.html"),"<!doctype html><p>popup</p>");fs.writeFileSync(path.join(dir,"options.html"),"<!doctype html><p>options</p>");return dir;}
test("discovers MV3 extension permission and execution surfaces without treating inference as authority",()=>{const dir=fixture();const d=discoverBrowserExtensionProject(dir);assert.equal(d.manifest.manifest_version,3);assert.deepEqual(d.permissions.declared,["activeTab","scripting","storage"]);assert.deepEqual(d.permissions.host,["https://example.test/*"]);assert.equal(d.files.missing.length,0);assert.ok(d.source_scan.api_namespaces.includes("tabs"));assert.ok(d.source_scan.api_namespaces.includes("storage"));const c=contractFromDiscovery(d,{product:"Fixture"});assert.equal(c.review_required,true);assert.ok(c.checks.every(x=>x.provenance.source==="inferred"&&x.provenance.reviewed===false));});
test("source scan separates remote executable references and dynamic-code evidence",()=>{const dir=fixture();fs.writeFileSync(path.join(dir,"bad.html"),'<script src="https://cdn.example.test/app.js"></script>');fs.writeFileSync(path.join(dir,"dynamic.js"),'const f = new Function("return 1")');const scan=scanSources(dir);assert.ok(scan.remote_executable_references.some(x=>x.kind==="remote-script"));assert.ok(scan.dynamic_code_patterns.some(x=>x.kind==="new-function"));});
test("capture normalizes runtime grants, service worker, storage topology and extension pages",async()=>{const dir=fixture();const driver={capture:async()=>({loaded:true,extensionId:"abc",serviceWorkers:[{url:"chrome-extension://abc/service-worker.js"}],grantedPermissions:{permissions:["scripting","storage","activeTab"],origins:["https://example.test/*"]},storageKeys:{local:["ready"],sync:[],session:["cache"]},dynamicContentScripts:[{id:"dynamic-1",matches:["https://example.test/*"],world:"ISOLATED"}],errors:[],popup:{loaded:true},options:{loaded:true},targetPage:{loaded:true,url:"https://example.test/"},environment:{browser:"fixture"}})};const result=await captureBrowserExtension({projectDir:dir,driver,options:{targetUrl:"https://example.test/"}});assert.equal(result.adapter,"browser-extension");assert.ok(result.observations.some(x=>x.id==="extension-service-worker-active"&&x.value===true));assert.ok(result.observations.some(x=>x.id==="runtime-granted-permissions"&&x.value.includes("storage")));assert.ok(result.observations.some(x=>x.id==="storage-local-keys"&&x.value[0]==="ready"));assert.ok(result.observations.some(x=>x.id==="popup-loads"&&x.value===true));assert.ok(result.observations.every(x=>x.protocol==="calibration-observation/0.2"));});
