"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {discoverCliProject,contractFromDiscovery,contractFromPlan,createProcessDriver,captureCli,normalizeCliPlan}=require("../src/adapters/cli");const {containerCommand}=require("../src/adapters/cli/process-driver");

test("CLI discovery finds package bin without executing it",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-cli-"));fs.mkdirSync(path.join(dir,"bin"));fs.writeFileSync(path.join(dir,"package.json"),JSON.stringify({name:"fixture-cli",version:"1.0.0",bin:{fixture:"bin/fixture.js"}}));fs.writeFileSync(path.join(dir,"bin/fixture.js"),"throw new Error('must not execute during discovery');");const discovery=discoverCliProject(dir);assert.equal(discovery.signals.package_bin_count,1);assert.deepEqual(discovery.cli.entrypoints,["bin/fixture.js"]);const contract=contractFromDiscovery(discovery,{product:"Fixture CLI"});assert.equal(contract.review_required,true);assert.ok(contract.checks.every((check)=>check.provenance.reviewed===false));});

test("CLI capture defaults to copied workspace, isolated HOME, no shell, and leaves source workspace unchanged",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-cli-run-"));fs.writeFileSync(path.join(dir,"fixture.js"),`const fs=require("node:fs");fs.writeFileSync("out.txt","ok");console.log("token=TOPSECRET");`);const plan={protocol:"calibration-cli-plan/0.5",id:"fixture",command:process.execPath,args:["fixture.js"],cwd:".",watch:["out.txt"],expected_exit_codes:[0],expected_changed_paths:["out.txt"],expect_stderr_empty:true,max_duration_ms:5000,include_output:false};const result=await captureCli({plan,projectDir:dir,driver:createProcessDriver(),options:{confirmExecution:true}});assert.equal(result.observations.find((item)=>item.id==="cli.fixture.watch-changes-accepted").value,true);assert.equal(fs.existsSync(path.join(dir,"out.txt")),false);assert.ok(!JSON.stringify(result).includes("TOPSECRET"));const env=result.observations[0].environment;assert.equal(env.shell,false);assert.equal(env.workspace_copy,true);assert.equal(env.security_boundary,"workspace-copy");});

test("CLI service orchestration waits for readiness and tears down dependencies",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"cal-cli-service-"));const port=23000+Math.floor(Math.random()*10000);fs.writeFileSync(path.join(dir,"daemon.js"),`const http=require('node:http');const port=Number(process.env.PORT);const s=http.createServer((q,r)=>{r.end('ok')});s.listen(port,'127.0.0.1');process.on('SIGTERM',()=>s.close(()=>process.exit(0)));`);fs.writeFileSync(path.join(dir,"main.js"),"process.exit(0)");const plan={protocol:"calibration-cli-plan/0.5",id:"orchestrated",command:process.execPath,args:["main.js"],services:[{id:"api",command:process.execPath,args:["daemon.js"],env:{PORT:String(port)},ready:{type:"tcp",host:"127.0.0.1",port,timeout_ms:3000}}],expected_exit_codes:[0]};const result=await captureCli({plan,projectDir:dir,driver:createProcessDriver(),options:{confirmExecution:true}});assert.equal(result.observations.find(x=>x.id==="cli.orchestrated.service.api.ready").value,true);});

test("CLI TTY plans reject separate stderr assertions",()=>{assert.throws(()=>normalizeCliPlan({protocol:"calibration-cli-plan/0.5",command:"x",tty:true,expect_stderr_empty:true}),/PTYs merge|tty mode/i);});

test("Container sandbox plans are explicit and never silently downgrade",()=>{const plan=normalizeCliPlan({protocol:"calibration-cli-plan/0.5",command:"node",args:["app.js"],sandbox:{mode:"container",runtime:"docker",image:"node:20-bookworm-slim",network:"none"}});const wrapped=containerCommand(plan,"/tmp/project","/tmp/home","docker");assert.equal(wrapped.command,"docker");assert.ok(wrapped.args.includes("--network"));assert.ok(wrapped.args.includes("none"));assert.ok(wrapped.args.includes("--read-only"));assert.ok(wrapped.args.includes("node:20-bookworm-slim"));const contract=contractFromPlan(plan,{product:"Container CLI"});assert.ok(contract.checks.some(x=>x.id==="cli.default.security-boundary"&&x.expected==="container"));});

test("CLI capture requires explicit execution confirmation",async()=>{await assert.rejects(()=>captureCli({plan:{protocol:"calibration-cli-plan/0.5",command:process.execPath,args:["--version"]},projectDir:process.cwd(),driver:createProcessDriver(),options:{}}),/confirm-execution/);});
