"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {normalizeGamePlan}=require("../src/adapters/game/plan");const {contractFromPlan}=require("../src/adapters/game/contract");const {captureGame,readPointer,targetBoundary}=require("../src/adapters/game/capture");const {safeBridgePath}=require("../src/adapters/game/playwright-driver");
function plan(){return {protocol:"calibration-game-plan/0.1",bridge:{global:"__GAME__",script:"bridge.js",require_ephemeral:true},scenarios:[{id:"sale",checks:[{id:"cash",domain:"resources",pointer:"/cashDelta",expected:7000},{id:"removed",domain:"state",pointer:"/removed",expected:true}]}]};}
function driver(){return {capture:async()=>({bridge:{ready:true,ephemeral:true,protocol:"altru-game-calibration-bridge/0.1"},scenarios:[{id:"sale",completed:true,result:{cashDelta:7000,removed:true,privateState:{secret:"not exported"}}}],consoleErrors:[],environment:{browser:"fixture",isolated_context:true}})};}
test("normalizes a developer-owned game plan and builds authoritative checks",()=>{const normalized=normalizeGamePlan(plan());assert.equal(normalized.scenarios[0].id,"sale");assert.equal(normalized.allow_remote_target,false);const contract=contractFromPlan(plan(),{product:"Fixture Game"});assert.equal(contract.adapter,"game");assert.equal(contract.review_required,false);assert.ok(contract.checks.some(item=>item.id==="game.sale.cash"&&item.expected===7000));assert.ok(contract.checks.some(item=>item.id==="game.bridge.ephemeral"&&item.domain==="security"));assert.ok(contract.checks.some(item=>item.id==="game.console-errors"&&item.expected===0));});
test("game capture emits only selected scalar metrics from an ephemeral local scenario",async()=>{const result=await captureGame({plan:plan(),driver:driver(),url:"http://127.0.0.1:18789/game",options:{confirmExecution:true}});assert.equal(result.adapter,"game");assert.ok(result.observations.some(item=>item.id==="game.sale.cash"&&item.value===7000));assert.ok(result.observations.some(item=>item.id==="game.sale.removed"&&item.value===true));assert.ok(result.observations.some(item=>item.id==="game.console-errors"&&item.value===0));assert.equal(result.observations[0].environment.target_scope,"local");assert.equal(JSON.stringify(result).includes("not exported"),false);});
test("game capture requires explicit execution confirmation",async()=>{await assert.rejects(()=>captureGame({plan:plan(),driver:driver(),url:"http://127.0.0.1:18789/game",options:{confirmExecution:false}}),/confirm-execution/);});
test("remote game execution requires plan and operator consent",async()=>{await assert.rejects(()=>captureGame({plan:plan(),driver:driver(),url:"https://example.test/game",options:{confirmExecution:true}}),/allow_remote_target/);const remotePlan={...plan(),allow_remote_target:true};await assert.rejects(()=>captureGame({plan:remotePlan,driver:driver(),url:"https://example.test/game",options:{confirmExecution:true}}),/allow-remote-target/);const result=await captureGame({plan:remotePlan,driver:driver(),url:"https://example.test/game",options:{confirmExecution:true,allowRemoteTarget:true}});assert.equal(result.observations[0].environment.target_scope,"remote");});
test("persistent game state requires explicit operator consent",async()=>{const persistent={...plan(),bridge:{...plan().bridge,require_ephemeral:false}};await assert.rejects(()=>captureGame({plan:persistent,driver:driver(),url:"http://127.0.0.1:18789/game",options:{confirmExecution:true}}),/allow-persistent-state/);const persistentDriver={capture:async()=>({bridge:{ready:true,ephemeral:false,protocol:"altru-game-calibration-bridge/0.1"},scenarios:[{id:"sale",completed:true,result:{cashDelta:7000,removed:true}}],consoleErrors:[],environment:{browser:"fixture",isolated_context:true}})};const result=await captureGame({plan:persistent,driver:persistentDriver,url:"http://127.0.0.1:18789/game",options:{confirmExecution:true,allowPersistentState:true}});assert.equal(result.adapter,"game");});
test("target boundary accepts file and loopback targets but classifies public origins as remote",()=>{assert.equal(targetBoundary("file:///tmp/game/index.html").local,true);assert.equal(targetBoundary("http://localhost:8000/").local,true);assert.equal(targetBoundary("http://127.0.0.1:8000/").local,true);assert.equal(targetBoundary("https://example.test/").local,false);assert.throws(()=>targetBoundary("javascript:alert(1)"),/file, http, or https/);});
test("JSON pointer selection is deterministic and reports missing paths",()=>{assert.deepEqual(readPointer({a:{b:true}},"/a/b"),{found:true,value:true});assert.equal(readPointer({a:{}},"/a/b").found,false);});
test("bridge script path cannot escape the plan directory, including through symlinks",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"cal-game-"));const outside=fs.mkdtempSync(path.join(os.tmpdir(),"cal-game-outside-"));fs.writeFileSync(path.join(root,"bridge.js"),"void 0");fs.writeFileSync(path.join(outside,"outside.js"),"void 0");assert.equal(safeBridgePath(root,"bridge.js"),fs.realpathSync(path.join(root,"bridge.js")));assert.throws(()=>safeBridgePath(root,"../escape.js"),/stay inside/);const link=path.join(root,"linked.js");try{fs.symlinkSync(path.join(outside,"outside.js"),link);assert.throws(()=>safeBridgePath(root,"linked.js"),/symlink must stay inside/);}catch(error){if(error.code!=="EPERM"&&error.code!=="EACCES")throw error;}});
