"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const crypto=require("node:crypto");
const {createReleaseManifest,assertReleaseManifest,verifyReleaseTree,signReleaseManifest,verifyReleaseSignature}=require("../src/release/manifest");
function temp(){return fs.mkdtempSync(path.join(os.tmpdir(),"cal-release-"));}
function fixture(){const root=temp();fs.mkdirSync(path.join(root,"app"));fs.writeFileSync(path.join(root,"app","a.txt"),"alpha");fs.writeFileSync(path.join(root,"app","b.txt"),"beta");return root;}
function runtime(){return{browser:{chromium_installed:true,playwright_version:"1.62.1",browser_version:"Chromium fixture"}};}
test("release manifest v0.2 identity is deterministic across created_at timestamps",()=>{const root=fixture();const a=createReleaseManifest({rootDir:root,version:"0.11.0-alpha.0",runtime:runtime(),createdAt:"2026-08-10T01:00:00Z"});const b=createReleaseManifest({rootDir:root,version:"0.11.0-alpha.0",runtime:runtime(),createdAt:"2026-08-10T02:00:00Z"});assert.equal(a.schema,"altru-calibration-release-manifest/0.2");assert.equal(a.fingerprint,b.fingerprint);assert.equal(a.id,b.id);assert.notEqual(a.created_at,b.created_at);assertReleaseManifest(a);});
test("release tree verification rejects modified, missing, extra and symlinked payloads",()=>{const root=fixture();const manifest=createReleaseManifest({rootDir:root,version:"0.11.0-alpha.0",runtime:runtime()});assert.equal(verifyReleaseTree({rootDir:root,manifest}).status,"verified");fs.appendFileSync(path.join(root,"app","a.txt"),"tamper");assert.throws(()=>verifyReleaseTree({rootDir:root,manifest}),/integrity mismatch/);const root2=fixture(),manifest2=createReleaseManifest({rootDir:root2,version:"0.11.0-alpha.0",runtime:runtime()});fs.writeFileSync(path.join(root2,"extra.txt"),"extra");assert.throws(()=>verifyReleaseTree({rootDir:root2,manifest:manifest2}),/missing or unlisted files/);const root3=fixture();try{fs.symlinkSync(path.join(root3,"app","a.txt"),path.join(root3,"link.txt"));assert.throws(()=>createReleaseManifest({rootDir:root3,version:"0.11.0-alpha.0",runtime:runtime()}),/forbidden symlink/);}catch(error){if(error.code!=="EPERM"&&error.code!=="EACCES")throw error;}});
test("Ed25519 signatures require the independently supplied trusted key",()=>{const root=fixture();const manifest=createReleaseManifest({rootDir:root,version:"0.11.0-alpha.0",runtime:runtime()});const trusted=crypto.generateKeyPairSync("ed25519"),wrong=crypto.generateKeyPairSync("ed25519");const privateKeyPem=trusted.privateKey.export({type:"pkcs8",format:"pem"});const publicKeyPem=trusted.publicKey.export({type:"spki",format:"pem"});const wrongPublic=wrong.publicKey.export({type:"spki",format:"pem"});const signature=signReleaseManifest({manifest,privateKeyPem});assert.equal(verifyReleaseSignature({manifest,signature,publicKeyPem}).status,"verified");assert.throws(()=>verifyReleaseSignature({manifest,signature,publicKeyPem:wrongPublic}),/verification failed/);});
test("tampered release metadata invalidates manifest identity before signature verification",()=>{const root=fixture();const manifest=createReleaseManifest({rootDir:root,version:"0.11.0-alpha.0",runtime:runtime()});const pair=crypto.generateKeyPairSync("ed25519");const signature=signReleaseManifest({manifest,privateKeyPem:pair.privateKey.export({type:"pkcs8",format:"pem"})});const tampered=JSON.parse(JSON.stringify(manifest));tampered.version="0.11.1";assert.throws(()=>verifyReleaseSignature({manifest:tampered,signature,publicKeyPem:pair.publicKey.export({type:"spki",format:"pem"})}),/fingerprint mismatch/);});
