"use strict";
const {createObservation,normalizeObservationSet}=require("../../public/adapter-contract");
const {normalizeGamePlan}=require("./plan");
function evidence(type,source,summary,value=null){return {type,source,summary,value};}
function decodePointerToken(token){return token.replace(/~1/g,"/").replace(/~0/g,"~");}
function readPointer(value,pointer){if(pointer==="")return {found:true,value};let current=value;for(const token of pointer.slice(1).split("/").map(decodePointerToken)){if(current===null||typeof current!=="object"||!Object.prototype.hasOwnProperty.call(current,token))return {found:false,value:null};current=current[token];}return {found:true,value:current};}
function isScalar(value){return value===null||["string","number","boolean"].includes(typeof value);}
function targetBoundary(target){let parsed;try{parsed=new URL(target);}catch{throw new Error("game target must be a valid file, http, or https URL");}if(parsed.protocol==="file:")return {local:true,protocol:"file:",origin:"file://"};if(!["http:","https:"].includes(parsed.protocol))throw new Error("game target must use file, http, or https");const host=parsed.hostname.toLowerCase();const local=host==="localhost"||host==="127.0.0.1"||host==="[::1]"||host==="::1";return {local,protocol:parsed.protocol,origin:parsed.origin};}
async function captureGame({plan,driver,url=null,options={}}){const normalized=normalizeGamePlan(plan);if(!driver||typeof driver.capture!=="function")throw new Error("game capture requires a compatible driver");if(options.confirmExecution!==true)throw new Error("game capture requires --confirm-execution because it injects and executes a local developer bridge script in an isolated browser context");const target=url||normalized.target_url;if(!target)throw new Error("game capture requires --url or plan.target_url");const boundary=targetBoundary(target);if(!boundary.local&&!(normalized.allow_remote_target===true&&options.allowRemoteTarget===true))throw new Error("remote game capture requires allow_remote_target:true in the plan and --allow-remote-target from the operator");if(normalized.bridge.require_ephemeral===false&&options.allowPersistentState!==true)throw new Error("persistent-state game capture requires bridge.require_ephemeral:false in the plan and --allow-persistent-state from the operator");const startedAt=new Date().toISOString();const raw=await driver.capture({url:target,plan:normalized,options});const env={...(raw.environment||{}),target_scope:boundary.local?"local":"remote",target_protocol:boundary.protocol};const observations=[];
observations.push(createObservation({id:"game.bridge.ready",adapter:"game",kind:"behavior",source:"game-bridge",value:Boolean(raw.bridge?.ready),evidence:[evidence("game-bridge","browser",raw.bridge?.ready?"Calibration bridge loaded":"Calibration bridge did not load",raw.bridge?.protocol||null)],environment:env}));
observations.push(createObservation({id:"game.bridge.ephemeral",adapter:"game",kind:"security",source:"game-bridge",value:Boolean(raw.bridge?.ephemeral),evidence:[evidence("game-bridge","browser",raw.bridge?.ephemeral?"Bridge declared ephemeral state":"Bridge did not declare ephemeral state",Boolean(raw.bridge?.ephemeral))],environment:env}));
const consoleErrors=Array.isArray(raw.consoleErrors)?raw.consoleErrors:[];observations.push(createObservation({id:"game.console-errors",adapter:"game",kind:"behavior",source:"console",value:consoleErrors.length,evidence:consoleErrors.slice(0,20).map(message=>evidence("console","page",String(message))),environment:env}));
const results=new Map((raw.scenarios||[]).map(item=>[item.id,item]));for(const scenario of normalized.scenarios){const result=results.get(scenario.id);const completed=Boolean(result&&result.completed===true);observations.push(createObservation({id:`game.${scenario.id}.completed`,adapter:"game",kind:"behavior",source:"game-scenario",value:completed,evidence:[evidence("game-scenario",scenario.id,completed?`Scenario '${scenario.id}' completed`:`Scenario '${scenario.id}' failed`,result?.error||null)],reproduction:`Run game scenario '${scenario.id}' with ${scenario.repetitions} repetition(s)${scenario.seed===null?"":` and seed ${scenario.seed}`}.`,environment:env}));if(!completed)continue;for(const check of scenario.checks){const selected=readPointer(result.result,check.pointer);if(!selected.found)continue;if(!isScalar(selected.value))throw new Error(`game check '${scenario.id}.${check.id}' selected a non-scalar value; use a bridge-computed scalar metric instead`);observations.push(createObservation({id:`game.${scenario.id}.${check.id}`,adapter:"game",kind:check.domain,source:"game-scenario",value:selected.value,evidence:[evidence("game-metric",`${scenario.id}${check.pointer||"/"}`,`Captured scalar game metric for '${check.id}'`,selected.value)],reproduction:`Run game scenario '${scenario.id}' and inspect '${check.pointer||"/"}'.`,environment:env}));}}
return normalizeObservationSet({adapter:"game",started_at:startedAt,completed_at:new Date().toISOString(),observations});}
module.exports={captureGame,readPointer,targetBoundary};
