"use strict";
const {normalizeGamePlan}=require("./plan");
function contractFromPlan(plan,options={}){const normalized=normalizeGamePlan(plan);const ephemeralExpected=normalized.bridge.require_ephemeral!==false;const checks=[
  {id:"game.bridge.ready",domain:"behavior",title:"Game calibration bridge is ready",expected:true,required:true,origin:"game browser bridge",investigate:"Confirm the calibration bridge script loaded after the game and exposes the declared bridge protocol."},
  {id:"game.bridge.ephemeral",domain:"security",title:ephemeralExpected?"Game calibration runs use an ephemeral state boundary":"Game calibration uses the explicitly requested persistent state boundary",expected:ephemeralExpected,required:true,origin:"game browser bridge",investigate:ephemeralExpected?"Do not calibrate against a real player profile. The bridge must execute scenarios against isolated in-memory or disposable state.":"Persistent-state calibration is effectful. Confirm that bridge.require_ephemeral:false was deliberate and that the operator supplied --allow-persistent-state."},
  {id:"game.console-errors",domain:"behavior",title:"Game calibration run has no browser console errors",expected:0,required:true,origin:"game browser runtime",investigate:"Inspect page errors and console errors emitted while the calibration bridge and scenarios execute."}
];for(const scenario of normalized.scenarios){checks.push({id:`game.${scenario.id}.completed`,domain:"behavior",title:`${scenario.title}: scenario completes`,expected:true,required:true,origin:`game scenario ${scenario.id}`,investigate:"Inspect the scenario bridge, game console errors, timeout, and the last successful transition."});for(const check of scenario.checks){checks.push({id:`game.${scenario.id}.${check.id}`,domain:check.domain,title:check.title,expected:check.expected,required:check.required,allowDrift:check.allow_drift,severity:check.severity||undefined,origin:`game scenario ${scenario.id} -> ${check.pointer||"/"}`,investigate:check.investigate||`Inspect scenario '${scenario.id}' and the game state represented by '${check.pointer||"/"}'.`});}}
return {protocol:"calibration-contract/0.2",product:options.product||"Game calibration plan",adapter:"game",source:"developer-plan",review_required:false,checks};}
module.exports={contractFromPlan};
