"use strict";
const DOMAINS=new Set(["behavior","permissions","state","resources","security","environment","timing","history"]);
const SCALAR_TYPES=new Set(["string","number","boolean"]);
function scalar(value){return value===null||SCALAR_TYPES.has(typeof value);}
function text(value,fallback=""){return value==null?fallback:String(value);}
function normalizePointer(value,id){const pointer=text(value,"");if(pointer!==""&&!pointer.startsWith("/"))throw new Error(`game check '${id}' pointer must be empty or begin with '/'`);return pointer;}
function normalizeGameCheck(input={},index,scenarioId){const id=text(input.id,`check-${index+1}`);if(!/^[a-zA-Z0-9._-]{1,80}$/.test(id))throw new Error(`game check id '${id}' is invalid`);const domain=text(input.domain||input.kind,"behavior");if(!DOMAINS.has(domain))throw new Error(`game check '${id}' has unsupported domain '${domain}'`);if(!Object.prototype.hasOwnProperty.call(input,"expected"))throw new Error(`game check '${id}' requires expected`);if(!scalar(input.expected))throw new Error(`game check '${id}' expected value must be a JSON scalar`);return {id,domain,title:text(input.title,`${scenarioId}: ${id}`),pointer:normalizePointer(input.pointer,id),expected:input.expected,required:input.required!==false,allow_drift:input.allow_drift===true||input.allowDrift===true,severity:input.severity==null?null:text(input.severity),investigate:input.investigate==null?null:text(input.investigate)};}
function normalizeScenario(input={},index){const id=text(input.id,`scenario-${index+1}`);if(!/^[a-zA-Z0-9._-]{1,80}$/.test(id))throw new Error(`game scenario id '${id}' is invalid`);const checks=Array.isArray(input.checks)?input.checks.map((check,i)=>normalizeGameCheck(check,i,id)):[];if(!checks.length)throw new Error(`game scenario '${id}' requires at least one check`);const ids=new Set();for(const check of checks){if(ids.has(check.id))throw new Error(`duplicate game check '${check.id}' in scenario '${id}'`);ids.add(check.id);}return {id,title:text(input.title,id),seed:Number.isInteger(Number(input.seed))?Number(input.seed):null,repetitions:Number.isInteger(Number(input.repetitions))?Math.max(1,Math.min(10000,Number(input.repetitions))):1,timeout_ms:Number.isFinite(Number(input.timeout_ms))?Math.max(100,Math.min(300000,Number(input.timeout_ms))):30000,checks};}
function normalizeGamePlan(input={}){if(input.protocol&&input.protocol!=="calibration-game-plan/0.1")throw new Error("game plan protocol must be calibration-game-plan/0.1");const bridge=input.bridge&&typeof input.bridge==="object"?input.bridge:{};const globalName=text(bridge.global,"__ALTRU_CALIBRATION_GAME__");if(!/^[A-Za-z_$][A-Za-z0-9_$]{0,79}$/.test(globalName))throw new Error("game bridge global must be a simple JavaScript identifier");const script=text(bridge.script,"");if(!script)throw new Error("game plan requires bridge.script");const scenarios=Array.isArray(input.scenarios)?input.scenarios.map(normalizeScenario):[];if(!scenarios.length)throw new Error("game plan requires at least one scenario");const ids=new Set();for(const scenario of scenarios){if(ids.has(scenario.id))throw new Error(`duplicate game scenario id: ${scenario.id}`);ids.add(scenario.id);}return {protocol:"calibration-game-plan/0.1",target_url:input.target_url==null?null:text(input.target_url),allow_remote_target:input.allow_remote_target===true,bridge:{global:globalName,script,protocol:text(bridge.protocol,"altru-game-calibration-bridge/0.1"),require_ephemeral:bridge.require_ephemeral!==false},scenarios};}
module.exports={normalizeGamePlan,normalizeGameCheck,normalizeScenario,scalar};
