"use strict";
const fs=require("node:fs");const path=require("node:path");const YAML=require("yaml");
const SPEC_CANDIDATES=["openapi.json","swagger.json","api/openapi.json","api/swagger.json","docs/openapi.json","docs/swagger.json"];
const YAML_CANDIDATES=["openapi.yaml","openapi.yml","swagger.yaml","swagger.yml","api/openapi.yaml","api/openapi.yml","api/swagger.yaml","api/swagger.yml","docs/openapi.yaml","docs/openapi.yml","docs/swagger.yaml","docs/swagger.yml"];
const HTTP_METHODS=new Set(["get","put","post","delete","options","head","patch","trace"]);
function existing(root,candidates){return candidates.find((relative)=>fs.existsSync(path.join(root,relative)))||null;}
function parseSpec(file,format){try{const text=fs.readFileSync(file,"utf8");const value=format==="yaml"?YAML.parse(text):JSON.parse(text);return {spec:value,error:null};}catch(error){return {spec:null,error:String(error?.message||error)};}}
function sanitizeUrl(value){try{const url=new URL(String(value));url.username="";url.password="";for(const key of [...url.searchParams.keys()])url.searchParams.set(key,"[REDACTED]");return url.toString();}catch{return String(value||"");}}
function collectOperations(spec){const result=[];for(const [route,item] of Object.entries(spec?.paths||{})){if(!item||typeof item!=="object")continue;for(const [method,operation] of Object.entries(item)){if(!HTTP_METHODS.has(method.toLowerCase())||!operation||typeof operation!=="object")continue;result.push({method:method.toUpperCase(),path:route,operation_id:operation.operationId||null,security_declared:Array.isArray(operation.security)||Array.isArray(spec.security),parameter_count:Array.isArray(operation.parameters)?operation.parameters.length:0,request_body:Boolean(operation.requestBody),response_codes:Object.keys(operation.responses||{}).sort()});}}return result.sort((a,b)=>`${a.path}:${a.method}`.localeCompare(`${b.path}:${b.method}`));}
function discoverApiProject(projectDir){const root=path.resolve(projectDir||process.cwd());const jsonRel=existing(root,SPEC_CANDIDATES);const yamlRel=existing(root,YAML_CANDIDATES);const selected=jsonRel||yamlRel;const format=jsonRel?"json":yamlRel?"yaml":null;const loaded=selected?parseSpec(path.join(root,selected),format):{spec:null,error:null};const spec=loaded.spec;const operations=spec?collectOperations(spec):[];const securitySchemes=Object.keys(spec?.components?.securitySchemes||spec?.securityDefinitions||{}).sort();const servers=Array.isArray(spec?.servers)?spec.servers.map((item)=>sanitizeUrl(item?.url)).filter(Boolean):spec?.host?[sanitizeUrl(`${spec.schemes?.[0]||"https"}://${spec.host}${spec.basePath||""}`)]:[];const version=spec?.openapi||spec?.swagger||null;const valid=Boolean(spec&&typeof spec==="object"&&spec.paths&&version);return {protocol:"calibration-discovery/0.5",adapter:"api",root,files:{openapi_json:jsonRel,openapi_yaml:yamlRel,selected_spec:selected},signals:{specification_found:Boolean(selected),specification_loaded:Boolean(spec),specification_format:format,json_specification_loaded:Boolean(spec&&format==="json"),yaml_specification_loaded:Boolean(spec&&format==="yaml"),yaml_requires_conversion:false,specification_version:version,operation_count:operations.length,security_schemes:securitySchemes,server_count:servers.length,parse_error:Boolean(loaded.error)},api:{title:spec?.info?.title||null,version:spec?.info?.version||null,servers,operations,security_schemes:securitySchemes},inferred_expectations:[...(spec?[{id:"api-spec-loaded",domain:"behavior",title:"API specification loads successfully",expected:true,confidence:"high"}]:[]),...(spec?[{id:"api-operation-count",domain:"behavior",title:"Documented API operation count remains stable",expected:operations.length,confidence:"high"}]:[]),...(securitySchemes.length?[{id:"api-security-schemes",domain:"security",title:"Declared API security schemes remain stable",expected:securitySchemes,confidence:"high"}]:[])],review_required:true,note:valid?`${format.toUpperCase()} OpenAPI/Swagger discovery is evidence only. Review candidate expectations before treating them as the product contract.`:selected?`An API specification was found but could not be parsed as ${format.toUpperCase()}.`:"No OpenAPI/Swagger JSON or YAML specification was found."};}
module.exports={collectOperations,discoverApiProject,parseSpec,sanitizeUrl};
