"use strict";
const {sanitizeUrl}=require("./discover");
const SENSITIVE_HEADER=/^(authorization|proxy-authorization|cookie|set-cookie|x-api-key|api-key|x-auth-token)$/i;
function redactHeaderNames(headers){return Object.keys(headers||{}).map(String).sort();}
function authPresent(headers){return Object.keys(headers||{}).some((name)=>SENSITIVE_HEADER.test(name)||/authorization|token|api[-_]?key/i.test(name));}
function jsonShape(value){if(Array.isArray(value))return {type:"array",length:value.length,item_types:[...new Set(value.slice(0,25).map((item)=>Array.isArray(item)?"array":item===null?"null":typeof item))].sort()};if(value&&typeof value==="object")return {type:"object",keys:Object.keys(value).sort()};return {type:value===null?"null":typeof value};}
function redirectLocation(response,requestUrl){const location=response.headers.get("location");if(!location)return null;try{return sanitizeUrl(new URL(location,requestUrl).toString());}catch{return sanitizeUrl(location);}}
async function readBodyLimited(response,maxBytes){if(!response.body)return {bytes:0,truncated:false,text:""};const reader=response.body.getReader();const chunks=[];let total=0;let truncated=false;try{while(true){const {done,value}=await reader.read();if(done)break;if(total+value.byteLength>maxBytes){const remaining=Math.max(0,maxBytes-total);if(remaining)chunks.push(value.slice(0,remaining));total+=remaining;truncated=true;await reader.cancel().catch(()=>{});break;}chunks.push(value);total+=value.byteLength;}}finally{reader.releaseLock();}const merged=new Uint8Array(total);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.byteLength;}return {bytes:total,truncated,text:new TextDecoder().decode(merged)};}
function createHttpDriver(fetchImpl=globalThis.fetch){if(typeof fetchImpl!=="function")throw new Error("API capture requires a Fetch-compatible runtime");return {id:"node-fetch",async request({request,captureJson=false}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),request.timeout_ms);const started=Date.now();try{const init={method:request.method,headers:request.headers,redirect:"manual",signal:controller.signal};if(request.body!==null&&request.body!==undefined&&!["GET","HEAD"].includes(request.method)){if(typeof request.body==="string"||request.body instanceof Uint8Array)init.body=request.body;else{init.body=JSON.stringify(request.body);if(!Object.keys(request.headers).some((name)=>name.toLowerCase()==="content-type"))init.headers={...request.headers,"content-type":"application/json"};}}const response=await fetchImpl(request.url,init);const durationMs=Date.now()-started;const body=await readBodyLimited(response,request.max_response_bytes);const contentType=response.headers.get("content-type")||"";const redirectTarget=redirectLocation(response,request.url);let shape=null;let responseJson=null;if(!body.truncated&&/json/i.test(contentType)&&body.text){try{responseJson=JSON.parse(body.text);shape=jsonShape(responseJson);}catch{shape={type:"invalid-json"};responseJson=null;}}return {completed:true,status:response.status,ok:response.ok,url:sanitizeUrl(response.url||request.url),redirected:Boolean(response.redirected),redirectLocation:redirectTarget,durationMs,contentType,contentLength:response.headers.get("content-length"),responseBytes:body.bytes,responseTruncated:body.truncated,responseShape:shape,responseJson:captureJson?responseJson:null,requestHeaderNames:redactHeaderNames(request.headers),authorizationPresent:authPresent(request.headers),error:null,environment:{driver:"node-fetch",protocol:new URL(request.url).protocol.replace(":","")}};}catch(error){return {completed:false,status:null,ok:false,url:sanitizeUrl(request.url),redirected:false,redirectLocation:null,durationMs:Date.now()-started,contentType:"",contentLength:null,responseBytes:0,responseTruncated:false,responseShape:null,responseJson:null,requestHeaderNames:redactHeaderNames(request.headers),authorizationPresent:authPresent(request.headers),error:error?.name==="AbortError"?"request timed out":String(error?.message||error),environment:{driver:"node-fetch",protocol:new URL(request.url).protocol.replace(":","")}};}finally{clearTimeout(timer);}}};}
module.exports={authPresent,createHttpDriver,jsonShape,readBodyLimited,redactHeaderNames,redirectLocation};
