"use strict";
const SAFE_METHODS=new Set(["GET","HEAD","OPTIONS"]);const ASSERTION_OPERATORS=new Set(["exists","equals","type","length"]);
function normalizeExpectedStatus(value){const values=Array.isArray(value)?value:[value];return values.filter((item)=>Number.isInteger(Number(item))).map(Number);}
function normalizeHeaders(value){return value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([k,v])=>[String(k),String(v)])):{};}
function normalizeHttpRequest(input,id,{verification=false}={}){const method=String(input?.method||"GET").toUpperCase();const url=String(input?.url||"");if(!url)throw new Error(`api ${verification?"verification":"request"} '${id}' requires url`);let parsed;try{parsed=new URL(url);}catch{throw new Error(`api ${verification?"verification":"request"} '${id}' has invalid url`);}if(!["http:","https:"].includes(parsed.protocol))throw new Error(`api ${verification?"verification":"request"} '${id}' must use http or https`);if(parsed.username||parsed.password)throw new Error(`api ${verification?"verification":"request"} '${id}' must not contain URL userinfo`);if(verification&&!SAFE_METHODS.has(method))throw new Error(`api verification '${id}' must use a safe GET, HEAD, or OPTIONS request`);return {id,method,url,headers:normalizeHeaders(input.headers),body:input.body===undefined?null:input.body,timeout_ms:Number.isFinite(Number(input.timeout_ms))?Math.max(1,Number(input.timeout_ms)):10000,max_response_bytes:Number.isFinite(Number(input.max_response_bytes))?Math.max(1024,Number(input.max_response_bytes)):1048576,expected_status:input.expected_status===undefined?[]:normalizeExpectedStatus(input.expected_status),expected_content_type:input.expected_content_type==null?null:String(input.expected_content_type),max_duration_ms:Number.isFinite(Number(input.max_duration_ms))?Math.max(1,Number(input.max_duration_ms)):null,safe_method:SAFE_METHODS.has(method)};}
function normalizeAssertion(assertion,index,verifyId){const operator=String(assertion?.operator||"exists").toLowerCase();if(!ASSERTION_OPERATORS.has(operator))throw new Error(`api verification '${verifyId}' assertion ${index+1} has unsupported operator '${operator}'`);const pointer=assertion?.pointer==null?"":String(assertion.pointer);if(pointer!==""&&!pointer.startsWith("/"))throw new Error(`api verification '${verifyId}' assertion ${index+1} pointer must be empty or begin with '/'`);if(["equals","type","length"].includes(operator)&&!("expected" in (assertion||{})))throw new Error(`api verification '${verifyId}' assertion ${index+1} requires expected`);if(operator==="type"&&!new Set(["string","number","boolean","object","array","null"]).has(String(assertion.expected)))throw new Error(`api verification '${verifyId}' assertion ${index+1} has invalid expected type`);if(operator==="length"&&!Number.isInteger(Number(assertion.expected)))throw new Error(`api verification '${verifyId}' assertion ${index+1} length must be an integer`);return {pointer,operator,expected:assertion?.expected};}
function normalizeVerifier(input,index){const id=String(input?.id||`verify-${index+1}`);const base=normalizeHttpRequest(input,id,{verification:true});const assertions=Array.isArray(input.assertions)?input.assertions.map((item,i)=>normalizeAssertion(item,i,id)):[];return {...base,assertions};}
function normalizeApiPlan(input={}){if(input.protocol&&!new Set(["calibration-api-plan/0.4","calibration-api-plan/0.5"]).has(input.protocol))throw new Error("api plan protocol must be calibration-api-plan/0.4 or calibration-api-plan/0.5");if(!Array.isArray(input.requests)||input.requests.length===0)throw new Error("api plan requires at least one request");const ids=new Set();const requests=input.requests.map((request,index)=>{const id=String(request?.id||`request-${index+1}`);if(ids.has(id))throw new Error(`duplicate api request id: ${id}`);ids.add(id);const base=normalizeHttpRequest(request,id);const verifyIds=new Set();const verify=Array.isArray(request.verify)?request.verify.map((item,i)=>{const normalized=normalizeVerifier(item,i);if(verifyIds.has(normalized.id))throw new Error(`duplicate api verification id '${normalized.id}' in request '${id}'`);verifyIds.add(normalized.id);return normalized;}):[];return {...base,allow_effectful:Boolean(request.allow_effectful),verify};});return {protocol:"calibration-api-plan/0.5",requests};}
module.exports={ASSERTION_OPERATORS,SAFE_METHODS,normalizeApiPlan,normalizeAssertion,normalizeExpectedStatus,normalizeHttpRequest};
